version: '2.2'
services:
  router:
    image: nginx
    volumes:
      - ./conf/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl_certs
    links:
      - prod-ui:prod-ui
    depends_on:
      - prod-ui
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443

  prod-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod.ui
    command: node dist/server.js
    volumes:
      - ./ui/dist:/project/dist
